version: '3'

services:
  mqtt-ui:
    image: mqtt-ui:latest
    # For development only - use pre-built image for Wirenboard deployment
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - API_HOST=${API_HOST:-localhost}
      - API_PORT=${API_PORT:-8123}
      - API_PROTOCOL=${API_PROTOCOL:-http}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Remove the non-existent service dependency
    # depends_on:
    #   - api-server
    networks:
      - mqtt-network
    labels:
      - "com.wirenboard.description=MQTT UI Frontend"

  # For Wirenboard deployment, you'll typically connect to services already running
  # on the device rather than spinning up containers for them.
  # If you do need additional containers, define them here.

  # Example: Include Mosquitto MQTT broker if needed
  # mqtt-broker:
  #   image: arm32v7/eclipse-mosquitto:2.0
  #   restart: unless-stopped
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - /mnt/data/mosquitto/config:/mosquitto/config
  #     - /mnt/data/mosquitto/data:/mosquitto/data
  #     - /mnt/data/mosquitto/log:/mosquitto/log
  #   networks:
  #     - mqtt-network

networks:
  mqtt-network:
    driver: bridge 