/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint - service information.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/device/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Config
         * @description Get full configuration for a specific device.
         */
        get: operations["get_device_config_config_device__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Device Configs
         * @description Get configurations for all devices.
         *
         *     Returns a dictionary where:
         *     - Keys are device IDs (strings)
         *     - Values are device configuration objects with all device-specific settings
         *
         *     Each device configuration includes:
         *     - Basic device information (device_id, device_name, device_class, config_class)
         *     - MQTT topics and settings
         *     - Available commands and their parameters
         *     - Device-specific configuration sections (e.g., tv, emotiva, broadlink settings)
         *
         *     Returns:
         *         Dict[str, BaseDeviceConfig]: Dictionary mapping device IDs to their configurations
         */
        get: operations["get_all_device_configs_config_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Config
         * @description Get system configuration.
         */
        get: operations["get_system_config_config_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/persisted_states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Persisted States
         * @description Get the persisted states of all devices from the state store.
         *
         *     Returns:
         *         Dict[str, Any]: Dictionary mapping device IDs to their persisted states
         *
         *     Raises:
         *         HTTPException: If state persistence is not available
         */
        get: operations["get_all_persisted_states_devices_persisted_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Device Action
         * @description Execute an action on a specific device.
         *
         *     This endpoint allows executing various actions on devices. The available actions depend on the device type.
         *
         *     ## LG TV Actions:
         *
         *     * **move_cursor** - Move cursor to absolute position x,y
         *       ```json
         *       {
         *         "action": "move_cursor",
         *         "params": {
         *           "x": 500,
         *           "y": 300,
         *           "drag": false
         *         }
         *       }
         *       ```
         *
         *     * **move_cursor_relative** - Move cursor by dx,dy relative to current position
         *       ```json
         *       {
         *         "action": "move_cursor_relative",
         *         "params": {
         *           "dx": 100,
         *           "dy": -50,
         *           "drag": false
         *         }
         *       }
         *       ```
         *
         *     * **click** - Click at position x,y
         *       ```json
         *       {
         *         "action": "click",
         *         "params": {
         *           "x": 500,
         *           "y": 300
         *         }
         *       }
         *       ```
         *
         *     * **launch_app** - Launch an app by name
         *       ```json
         *       {
         *         "action": "launch_app",
         *         "params": {
         *           "app_name": "Netflix"
         *         }
         *       }
         *       ```
         *
         *     * **wake_on_lan** - Wake the TV using Wake-on-LAN
         *       ```json
         *       {
         *         "action": "wake_on_lan",
         *         "params": {}
         *       }
         *       ```
         *
         *     ## Emotiva XMC2 Actions:
         *
         *     * **power_on** - Turn the device on (supports zones)
         *       ```json
         *       {
         *         "action": "power_on",
         *         "params": {
         *           "zone": 1  # 1 for main zone, 2 for zone2
         *         }
         *       }
         *       ```
         *
         *     * **power_off** - Turn the device off (supports zones)
         *       ```json
         *       {
         *         "action": "power_off",
         *         "params": {
         *           "zone": 2  # This powers off zone 2
         *         }
         *       }
         *       ```
         *
         *     * **set_volume** - Set volume level (supports zones)
         *       ```json
         *       {
         *         "action": "set_volume",
         *         "params": {
         *           "level": -35.5,  # Volume in dB from -96.0 to 0.0
         *           "zone": 1  # 1 for main zone, 2 for zone2
         *         }
         *       }
         *       ```
         *
         *     * **mute_toggle** - Toggle mute state (supports zones)
         *       ```json
         *       {
         *         "action": "mute_toggle",
         *         "params": {
         *           "zone": 2  # This toggles mute for zone 2
         *         }
         *       }
         *       ```
         *
         *     * **set_input** - Change input source
         *       ```json
         *       {
         *         "action": "set_input",
         *         "params": {
         *           "input": "hdmi1"  # Input name (hdmi1-hdmi8, optical1-optical4, etc.)
         *         }
         *       }
         *       ```
         *
         *     ## Common Actions for Other Devices:
         *     * **power_on** - Turn the device on
         *     * **power_off** - Turn the device off
         *     * **set_volume** - Set device volume (params: volume)
         *     * **set_mute** - Set device mute state (params: mute)
         *     * **set_input_source** - Change input source (params: input_source)
         *     * **send_action** - Send remote control command (params: command)
         */
        post: operations["execute_device_action_devices__device_id__action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Actions By Groups
         * @description Get all actions for a device organized by groups, including empty groups.
         */
        get: operations["get_device_actions_by_groups_devices__device_id__groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/groups/{group_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Actions By Group
         * @description List all actions in a group for a device, with status information.
         */
        get: operations["get_actions_by_group_devices__device_id__groups__group_id__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/persisted_state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Persisted State
         * @description Get the persisted state of a specific device from the state store.
         *
         *     Args:
         *         device_id: The ID of the device to retrieve state for
         *
         *     Returns:
         *         JSON: The persisted device state
         *
         *     Raises:
         *         HTTPException: If state persistence is not available or no state found
         */
        get: operations["get_device_persisted_state_devices__device_id__persisted_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device State
         * @description Get information about a specific device's current state.
         *
         *     Args:
         *         device_id: The ID of the device to retrieve
         *
         *     Returns:
         *         Device-specific state (e.g., LgTvState, AppleTVState, EmotivaXMC2State, etc.)
         *         that extends BaseDeviceState with device-specific fields like volume, power,
         *         input sources, playback information, and other operational data.
         *
         *     Raises:
         *         HTTPException: If device is not found or an error occurs
         */
        get: operations["get_device_state_devices__device_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device Events Stream
         * @description Subscribe to real-time device events via Server-Sent Events
         */
        get: operations["devices_stream_events_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scenario Events Stream
         * @description Subscribe to real-time scenario events via Server-Sent Events
         */
        get: operations["scenarios_stream_events_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE Connection Statistics
         * @description Get current statistics about active Server-Sent Events connections
         */
        get: operations["get_sse_stats_events_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Events Stream
         * @description Subscribe to real-time system-wide events via Server-Sent Events
         */
        get: operations["system_stream_events_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/test/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Broadcast Test Event
         * @description Send a test event to a specific SSE channel for development and testing
         */
        post: operations["test_broadcast_events_test__channel__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Groups
         * @description List all available function groups.
         */
        get: operations["get_groups_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Message
         * @description Publish a message to an MQTT topic.
         *
         *     This endpoint allows publishing messages to an MQTT topic with the following features:
         *
         *     - **Optional payload**: If payload is not provided (null), it defaults to 1 (which will be sent as "1")
         *     - **Multiple payload types**: Payload can be a string, number, boolean, object, or array
         *     - **Type conversion**:
         *         - Dict/object payloads are JSON serialized
         *         - Boolean payloads are converted to "true"/"false" strings
         *         - Numeric payloads are converted to strings
         *
         *     ### Parameter-based Commands
         *
         *     For devices with commands that accept parameters, the payload should be a JSON object
         *     with properties matching the parameter names defined in the device configuration:
         *
         *     - **Set volume example**: For a command with a 'level' parameter
         *       ```json
         *       {
         *         "level": 50
         *       }
         *       ```
         *
         *     - **Launch app example**: For a command with an 'app' parameter
         *       ```json
         *       {
         *         "app": "Netflix"
         *       }
         *       ```
         *
         *     - **Multiple parameters example**: For commands with multiple parameters
         *       ```json
         *       {
         *         "temperature": 22.5,
         *         "mode": "heat"
         *       }
         *       ```
         *
         *     ### Device-Specific Command Examples
         *
         *     #### LG TV Commands
         *
         *     - **Move cursor to position**:
         *       ```json
         *       {
         *         "x": 500,
         *         "y": 300,
         *         "drag": false
         *       }
         *       ```
         *
         *     - **Click at position**:
         *       ```json
         *       {
         *         "x": 500,
         *         "y": 300
         *       }
         *       ```
         *
         *     #### Audio/Video Receiver Commands
         *
         *     - **Set volume with zone selection**:
         *       ```json
         *       {
         *         "level": -35.5,
         *         "zone": 1
         *       }
         *       ```
         *
         *     - **Change input source**:
         *       ```json
         *       {
         *         "input": "hdmi1"
         *       }
         *       ```
         *
         *     #### Wirenboard IR Commands
         *
         *     - **Send IR command with parameters**:
         *       ```json
         *       {
         *         "code": "POWER_ON",
         *         "repeat": 2
         *       }
         *       ```
         *
         *     ### Alternative Format
         *
         *     Some implementations may use a format that includes both action name and parameters:
         *
         *     ```json
         *     {
         *       "action": "set_volume",
         *       "params": {
         *         "level": -35.5,
         *         "zone": 1
         *       }
         *     }
         *     ```
         *
         *     The parameters will be validated according to their definitions in the device configuration.
         *
         *     Args:
         *         message: The MQTT message to publish
         *         background_tasks: FastAPI background tasks manager
         *
         *     Returns:
         *         MQTTPublishResponse with status of the operation
         *
         *     Raises:
         *         HTTPException: If service is not initialized or an error occurs
         */
        post: operations["publish_message_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reload System
         * @description Reload configurations and device modules.
         */
        post: operations["reload_system_reload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rooms
         * @description Get a list of all room definitions.
         *
         *     Returns:
         *         List[RoomDefinitionResponse]: List of room definitions
         *
         *     Raises:
         *         HTTPException: If service not initialized
         */
        get: operations["list_rooms_room_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Room
         * @description Get a specific room definition.
         *
         *     Args:
         *         room_id: The ID of the room to retrieve
         *
         *     Returns:
         *         RoomDefinitionResponse: The room definition
         *
         *     Raises:
         *         HTTPException: If room not found or service not initialized
         */
        get: operations["get_room_room__room_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/definition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenarios For Room
         * @description Get definitions of scenarios, optionally filtered by room.
         *
         *     Args:
         *         room: Optional room ID to filter scenarios by
         *
         *     Returns:
         *         List[ScenarioDefinition]: List of scenario definitions
         *
         *     Raises:
         *         HTTPException: If service not initialized
         */
        get: operations["get_scenarios_for_room_scenario_definition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/definition/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenario Definition
         * @description Get the definition of a specific scenario.
         *
         *     Returns:
         *         ScenarioDefinition: The scenario definition
         *
         *     Raises:
         *         HTTPException: If scenario not found or service not initialized
         */
        get: operations["get_scenario_definition_scenario_definition__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/role_action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Role Action
         * @description Execute an action on a device bound to a role in the current scenario.
         *
         *     Args:
         *         data: The role action request with role, command and params
         *
         *     Returns:
         *         Dict[str, Any]: The result of the command execution
         *
         *     Raises:
         *         HTTPException: If no active scenario or an error occurs
         */
        post: operations["execute_role_action_scenario_role_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Shutdown Scenario
         * @description Shutdown the currently active scenario.
         *
         *     This endpoint shuts down the currently active scenario if it matches the provided ID.
         *     If no scenario is active or the active scenario doesn't match the provided ID,
         *     it returns an appropriate error.
         *
         *     Args:
         *         data: The shutdown scenario request with scenario ID and graceful flag
         *
         *     Returns:
         *         ScenarioResponse: Status of the operation
         *
         *     Raises:
         *         HTTPException: If no active scenario, scenario mismatch, or an error occurs
         */
        post: operations["shutdown_scenario_scenario_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Scenario
         * @description Start a scenario if no scenario is currently active.
         *
         *     This endpoint starts a scenario only if there is no currently active scenario.
         *     If a scenario is already running, it returns an error.
         *
         *     Args:
         *         data: The start scenario request with scenario ID
         *
         *     Returns:
         *         ScenarioResponse: Status of the operation
         *
         *     Raises:
         *         HTTPException: If scenario not found, another scenario is active, or an error occurs
         */
        post: operations["start_scenario_scenario_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenario State
         * @description Get the current scenario state.
         *
         *     Returns information about the active scenario and the state of all
         *     devices that are part of it.
         *
         *     Returns:
         *         ScenarioState: Current scenario state
         *
         *     Raises:
         *         HTTPException: If no active scenario or service not initialized
         */
        get: operations["get_scenario_state_scenario_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Scenario
         * @description Switch to a different scenario.
         *
         *     This endpoint performs a transition between scenarios, handling
         *     device state changes efficiently.
         *
         *     Args:
         *         data: The switch scenario request with scenario ID and graceful flag
         *
         *     Returns:
         *         ScenarioResponse: Status of the operation
         *
         *     Raises:
         *         HTTPException: If scenario not found or an error occurs
         */
        post: operations["switch_scenario_scenario_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/virtual_config/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenario Virtual Config
         * @description Get the virtual WB device configuration for a specific scenario.
         *
         *     This endpoint returns the virtual BaseDeviceConfig-compatible configuration
         *     that represents how a scenario appears as a WB virtual device. The configuration
         *     is generated dynamically from the scenario definition and includes:
         *     - Virtual commands (startup/shutdown and role-based commands)
         *     - WB control metadata and types
         *     - Parameter definitions inherited from role devices
         *
         *     Args:
         *         id: Scenario ID to get virtual config for
         *
         *     Returns:
         *         ScenarioWBConfig: The virtual WB device configuration
         *
         *     Raises:
         *         HTTPException: If scenario not found, service not initialized, or error occurs
         */
        get: operations["get_scenario_virtual_config_scenario_virtual_config__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/virtual_configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Scenario Virtual Configs
         * @description Get virtual WB device configurations for all available scenarios.
         *
         *     This endpoint returns a mapping of scenario IDs to their virtual WB device
         *     configurations. For scenarios that are currently active, it returns the
         *     cached configuration. For inactive scenarios, it generates the configuration
         *     on-demand.
         *
         *     Returns:
         *         Dict[str, ScenarioWBConfig]: Mapping of scenario ID to virtual config
         *
         *     Raises:
         *         HTTPException: If service not initialized or error occurs
         */
        get: operations["get_all_scenario_virtual_configs_scenario_virtual_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/{scenario_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specific Scenario State
         * @description Get the state of a specific scenario by ID.
         *
         *     Returns the scenario state including device states if the scenario is currently active,
         *     or a basic state structure with empty device states if the scenario is inactive.
         *
         *     Args:
         *         scenario_id: The ID of the scenario to retrieve state for
         *
         *     Returns:
         *         ScenarioState: The scenario state with device information
         *
         *     Raises:
         *         HTTPException: If scenario is not found or service not initialized
         */
        get: operations["get_specific_scenario_state_scenario__scenario_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get System Info
         * @description Get system information.
         */
        get: operations["get_system_info_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionGroup
         * @description Schema for a group of actions.
         */
        ActionGroup: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Group Id */
            group_id: string;
            /** Group Name */
            group_name: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * ActionRequest
         * @description Request model for executing a role action.
         */
        ActionRequest: {
            /** Command */
            command: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /** Role */
            role: string;
        };
        /**
         * AppleTVState
         * @description Schema for Apple TV device state.
         */
        AppleTVState: {
            /**
             * Album
             * @default null
             */
            album: string | null;
            /**
             * App
             * @default null
             */
            app: string | null;
            /**
             * Artist
             * @default null
             */
            artist: string | null;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Ip Address
             * @default null
             */
            ip_address: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /**
             * Media Type
             * @default null
             */
            media_type: string | null;
            /**
             * Playback State
             * @default null
             */
            playback_state: string | null;
            /**
             * Position
             * @default null
             */
            position: number | null;
            /**
             * Power
             * @default off
             */
            power: string;
            /**
             * Title
             * @default null
             */
            title: string | null;
            /**
             * Total Time
             * @default null
             */
            total_time: number | null;
            /**
             * Volume
             * @default null
             */
            volume: number | null;
        };
        /**
         * AuralicDeviceState
         * @description Schema for Auralic device state.
         *
         *     The power state can have the following values:
         *     - "on": Device is powered on and operational
         *     - "off": Device is in standby mode (UPnP control) or deep sleep mode (IR control)
         *
         *     When the device is in deep sleep mode, connected will be False and power will be "off".
         */
        AuralicDeviceState: {
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /**
             * Deep Sleep
             * @default false
             */
            deep_sleep: boolean;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Ip Address
             * @default null
             */
            ip_address: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
            /**
             * Mute
             * @default false
             */
            mute: boolean;
            /**
             * Power
             * @default off
             */
            power: string;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /**
             * Track Album
             * @default null
             */
            track_album: string | null;
            /**
             * Track Artist
             * @default null
             */
            track_artist: string | null;
            /**
             * Track Title
             * @default null
             */
            track_title: string | null;
            /**
             * Transport State
             * @default null
             */
            transport_state: string | null;
            /**
             * Volume
             * @default 0
             */
            volume: number;
            /**
             * Warning
             * @default null
             */
            warning: string | null;
        };
        /**
         * BaseCommandConfig
         * @description Base schema for command configuration.
         */
        BaseCommandConfig: {
            /**
             * Action
             * @description Action identifier for this command
             */
            action?: string | null;
            /**
             * Description
             * @description Human-readable description of the command
             */
            description?: string | null;
            /**
             * Group
             * @description Functional group this command belongs to
             */
            group?: string | null;
            /**
             * Params
             * @description Parameter definitions for this command
             */
            params?: components["schemas"]["CommandParameterDefinition"][] | null;
        };
        /**
         * BaseDeviceConfig
         * @description Base schema for device configuration.
         */
        BaseDeviceConfig: {
            /** Commands */
            commands?: {
                [key: string]: components["schemas"]["BaseCommandConfig"];
            };
            /**
             * Config Class
             * @description The configuration model class name (e.g., 'LgTvDeviceConfig')
             */
            config_class: string;
            /**
             * @description The category of the device (e.g., 'device' or 'appliance')
             * @default device
             */
            device_category: components["schemas"]["DeviceCategory"];
            /**
             * Device Class
             * @description The device implementation class name (e.g., 'LgTv')
             */
            device_class: string;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Enable Wb Emulation
             * @description Enable Wirenboard virtual device emulation
             * @default true
             */
            enable_wb_emulation: boolean;
            /**
             * Wb Controls
             * @description Custom Wirenboard control definitions
             */
            wb_controls?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /**
             * Wb State Mappings
             * @description Custom state field to WB control mappings
             */
            wb_state_mappings?: {
                [key: string]: string | string[];
            } | null;
        };
        /**
         * BaseDeviceState
         * @description Base schema for device state.
         */
        BaseDeviceState: {
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /**
             * Power
             * @default off
             */
            power: string;
        };
        /**
         * BroadcastResponse
         * @description Response model for test broadcast operations
         */
        BroadcastResponse: {
            /**
             * Active Connections
             * @description Number of active connections that received the event
             * @example 3
             */
            active_connections: number;
            /**
             * Message
             * @description Descriptive message about the operation
             * @example Test event broadcasted to devices channel
             */
            message: string;
            /**
             * Status
             * @description Operation status
             * @example success
             */
            status: string;
        };
        /**
         * CommandParameterDefinition
         * @description Schema for command parameter definition.
         */
        CommandParameterDefinition: {
            /**
             * Default
             * @description Default value if parameter is not provided and not required
             */
            default?: unknown | null;
            /**
             * Description
             * @description Human-readable description
             */
            description?: string | null;
            /**
             * Max
             * @description Maximum allowed value (used with type: 'range')
             */
            max?: number | null;
            /**
             * Min
             * @description Minimum allowed value (used with type: 'range')
             */
            min?: number | null;
            /**
             * Name
             * @description Parameter name
             */
            name: string;
            /**
             * Required
             * @description Whether this parameter must be provided
             */
            required: boolean;
            /**
             * Type
             * @description Data type (e.g., 'string', 'integer', 'float', 'boolean', 'range')
             */
            type: string;
        };
        /**
         * CommandResponse
         * @description Return type for BaseDevice.execute_action.
         *
         *     This combines required fields (success, device_id, action, state)
         *     with optional fields (error, mqtt_command, data) to match FastAPI validation
         *     requirements while maintaining proper typing.
         */
        CommandResponse: {
            /** Action */
            action: string;
            /** Data */
            data?: unknown | null;
            /** Device Id */
            device_id: string;
            /** Error */
            error?: string | null;
            /** Mqtt Command */
            mqtt_command?: {
                [key: string]: unknown;
            } | null;
            state: components["schemas"]["BaseDeviceState"];
            /** Success */
            success: boolean;
        };
        /**
         * CommandStep
         * @description A step in a scenario sequence (startup or shutdown).
         */
        CommandStep: {
            /**
             * Command
             * @description Command name to execute
             */
            command: string;
            /**
             * Condition
             * @description Expression to evaluate against device state, run only if True
             */
            condition?: string | null;
            /**
             * Delay After Ms
             * @description Delay in milliseconds after executing this command
             * @default 0
             */
            delay_after_ms: number;
            /**
             * Device
             * @description Device ID to execute the command on
             */
            device: string;
            /**
             * Params
             * @description Command parameters
             */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * DeviceAction
         * @description Schema for device action requests.
         * @example {
         *       "action": "power_on"
         *     }
         * @example {
         *       "action": "set_volume",
         *       "params": {
         *         "volume": 50
         *       }
         *     }
         */
        DeviceAction: {
            /**
             * Action
             * @description Action to execute on the device
             */
            action: string;
            /**
             * Params
             * @description Optional parameters for the action
             */
            params?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * DeviceCategory
         * @description Enumeration for device categories.
         * @enum {string}
         */
        DeviceCategory: "device" | "appliance";
        /**
         * DeviceState
         * @description Runtime state of a device.
         */
        DeviceState: {
            /**
             * Extra
             * @description Additional device-specific state fields
             */
            extra?: {
                [key: string]: unknown;
            };
            /**
             * Input
             * @description Active input port
             */
            input?: string | null;
            /**
             * Output
             * @description Active output port
             */
            output?: string | null;
            /**
             * Power
             * @description True = ON, False = OFF
             */
            power?: boolean | null;
        };
        /**
         * EmotivaXMC2State
         * @description Schema for eMotiva XMC2 device state.
         */
        EmotivaXMC2State: {
            /**
             * Audio Bitstream
             * @default null
             */
            audio_bitstream: string | null;
            /**
             * Audio Input
             * @default null
             */
            audio_input: string | null;
            /**
             * Audio Mode
             * @default null
             */
            audio_mode: string | null;
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Input Source
             * @default null
             */
            input_source: string | null;
            /**
             * Ip Address
             * @default null
             */
            ip_address: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /**
             * Mac Address
             * @default null
             */
            mac_address: string | null;
            /**
             * Mute
             * @default null
             */
            mute: boolean | null;
            /**
             * Notifications
             * @default false
             */
            notifications: boolean;
            /**
             * Power
             * @default off
             */
            power: string;
            /**
             * Startup Complete
             * @default false
             */
            startup_complete: boolean;
            /**
             * Video Input
             * @default null
             */
            video_input: string | null;
            /**
             * Volume
             * @default null
             */
            volume: number | null;
            /**
             * Zone2 Mute
             * @default null
             */
            zone2_mute: boolean | null;
            /**
             * Zone2 Power
             * @default null
             */
            zone2_power: string | null;
            /**
             * Zone2 Volume
             * @default null
             */
            zone2_volume: number | null;
        };
        /**
         * ErrorResponse
         * @description Schema for error responses.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Error Code */
            error_code?: string | null;
        };
        /**
         * Group
         * @description Schema for a function group.
         */
        Group: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * GroupActionsResponse
         * @description Schema for API responses that return actions for a specific group with status information.
         */
        GroupActionsResponse: {
            /** Actions */
            actions?: {
                [key: string]: unknown;
            }[];
            /** Device Id */
            device_id: string;
            /** Group Id */
            group_id: string;
            /** Group Name */
            group_name?: string | null;
            /** Message */
            message?: string | null;
            /** Status */
            status: string;
        };
        /**
         * GroupedActionsResponse
         * @description Schema for API responses that return actions grouped by function.
         */
        GroupedActionsResponse: {
            /**
             * Default Included
             * @default false
             */
            default_included: boolean;
            /** Device Id */
            device_id: string;
            /** Groups */
            groups: components["schemas"]["ActionGroup"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KitchenHoodState
         * @description Schema for kitchen hood state.
         */
        KitchenHoodState: {
            /** Connection Status */
            connection_status: string;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /** Light */
            light: string;
            /**
             * Power
             * @default off
             */
            power: string;
            /** Speed */
            speed: number;
        };
        /**
         * LastCommand
         * @description Schema for last executed command.
         */
        LastCommand: {
            /** Action */
            action: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            } | null;
            /** Source */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * LgTvState
         * @description Schema for LG TV state.
         */
        LgTvState: {
            /** Connected */
            connected: boolean;
            /** Current App */
            current_app: string | null;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** Input Source */
            input_source: string | null;
            /** Ip Address */
            ip_address: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /** Mac Address */
            mac_address: string | null;
            /** Mute */
            mute: boolean;
            /**
             * Power
             * @default off
             */
            power: string;
            /**
             * Volume
             * @default null
             */
            volume: number | null;
        };
        /**
         * MQTTBrokerConfig
         * @description Schema for MQTT broker configuration.
         */
        MQTTBrokerConfig: {
            /** Auth */
            auth?: {
                [key: string]: string;
            } | null;
            /** Client Id */
            client_id: string;
            /** Host */
            host: string;
            /**
             * Keepalive
             * @default 60
             */
            keepalive: number;
            /** Port */
            port: number;
        };
        /**
         * MQTTMessage
         * @description Schema for MQTT messages.
         * @example {
         *       "payload": "on",
         *       "qos": 1,
         *       "retain": false,
         *       "topic": "/devices/light/set"
         *     }
         * @example {
         *       "payload": 22.5,
         *       "qos": 1,
         *       "retain": true,
         *       "topic": "/devices/thermostat/set_temp"
         *     }
         * @example {
         *       "payload": {
         *         "action": "channel",
         *         "value": 5
         *       },
         *       "qos": 0,
         *       "retain": false,
         *       "topic": "/devices/tv/command"
         *     }
         */
        MQTTMessage: {
            /**
             * Payload
             * @description Message payload to publish. Can be string, number, boolean, object, or array. If not provided, defaults to 1.
             */
            payload?: string | number | {
                [key: string]: unknown;
            } | unknown[] | boolean | null;
            /**
             * Qos
             * @description Quality of Service level (0, 1, or 2)
             * @default 0
             */
            qos: number;
            /**
             * Retain
             * @description Whether to retain the message on the broker
             * @default false
             */
            retain: boolean;
            /**
             * Topic
             * @description MQTT topic to publish the message to
             */
            topic: string;
        };
        /**
         * MQTTPublishResponse
         * @description Schema for MQTT publish response.
         */
        MQTTPublishResponse: {
            /** Error */
            error?: string | null;
            /** Message */
            message: string;
            /** Success */
            success: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Topic */
            topic: string;
        };
        /**
         * MaintenanceConfig
         * @description Configuration for system maintenance settings.
         */
        MaintenanceConfig: {
            /**
             * Duration
             * @description Maintenance duration in minutes
             */
            duration: number;
            /**
             * Topic
             * @description MQTT topic to monitor for maintenance status
             */
            topic: string;
        };
        /**
         * ManualInstructions
         * @description Instructions that require human intervention (cannot be automated).
         */
        ManualInstructions: {
            /**
             * Shutdown
             * @description Steps to perform when shutting down the scenario
             */
            shutdown?: string[];
            /**
             * Startup
             * @description Steps to perform when starting the scenario
             */
            startup?: string[];
        };
        /**
         * PersistedStatesResponse
         * @description Model for the collection of persisted device states.
         */
        PersistedStatesResponse: {
            [key: string]: {
                [key: string]: unknown;
            };
        };
        /**
         * PersistenceConfig
         * @description Configuration for the persistence layer.
         */
        PersistenceConfig: {
            /**
             * Db Path
             * @description Path to the SQLite database file
             * @default data/state_store.db
             */
            db_path: string;
        };
        /**
         * ReloadResponse
         * @description Schema for system reload response.
         */
        ReloadResponse: {
            /** Message */
            message?: string | null;
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /**
         * RevoxA77ReelToReelState
         * @description Schema for Revox A77 reel-to-reel state.
         */
        RevoxA77ReelToReelState: {
            /** Connection Status */
            connection_status: string;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /**
             * Power
             * @default off
             */
            power: string;
        };
        /**
         * RoomDefinitionResponse
         * @description Response model for room definitions.
         */
        RoomDefinitionResponse: {
            /** Default Scenario */
            default_scenario?: string | null;
            /** Description */
            description: string;
            /** Devices */
            devices: string[];
            /** Names */
            names: {
                [key: string]: string;
            };
            /** Room Id */
            room_id: string;
        };
        /**
         * SSEStats
         * @description SSE connection statistics response model
         */
        SSEStats: {
            /**
             * Active Connections
             * @description Number of active connections per channel
             * @example {
             *       "devices": 3,
             *       "scenarios": 1,
             *       "system": 2
             *     }
             */
            active_connections: {
                [key: string]: number;
            };
            /**
             * Channels
             * @description List of available SSE channels
             * @example [
             *       "devices",
             *       "scenarios",
             *       "system"
             *     ]
             */
            channels: string[];
            /**
             * Total Connections
             * @description Total number of active connections across all channels
             * @example 6
             */
            total_connections: number;
        };
        /**
         * ScenarioDefinition
         * @description Declarative definition of a scenario.
         *
         *     Two formats are supported during the redesign migration:
         *
         *     - **thin** (preferred): a ``source``/``display``/``audio`` selection. Device membership,
         *       input values, and ordering are derived from ``config/topology.json`` by the reconciler;
         *       ``devices`` and the sequences are left empty.
         *     - **legacy / escape hatch**: explicit ``devices`` + ``startup_sequence``/``shutdown_sequence``.
         *
         *     See docs/scenarios/scenario_system_redesign.md §6.
         */
        ScenarioDefinition: {
            /**
             * Audio
             * @description Active audio device id; binds the volume/mute roles
             */
            audio?: string | null;
            /**
             * Description
             * @description Description of the scenario's purpose
             * @default
             */
            description: string;
            /**
             * Devices
             * @description Explicit device list (legacy format)
             */
            devices?: string[];
            /**
             * Display
             * @description Primary video sink device id
             */
            display?: string | null;
            /** @description Instructions requiring human intervention */
            manual_instructions?: components["schemas"]["ManualInstructions"] | null;
            /**
             * Name
             * @description Human-readable name
             */
            name: string;
            /**
             * Roles
             * @description Mapping of role name to device ID
             */
            roles?: {
                [key: string]: string;
            };
            /**
             * Room Id
             * @description If set, declares the primary room this scenario runs in. All devices must be in this room.
             */
            room_id?: string | null;
            /**
             * Scenario Id
             * @description Unique identifier for the scenario
             */
            scenario_id: string;
            /**
             * Shutdown Sequence
             * @description Explicit shutdown steps (legacy / escape hatch)
             */
            shutdown_sequence?: components["schemas"]["CommandStep"][];
            /**
             * Source
             * @description Primary content source device id
             */
            source?: string | null;
            /**
             * Startup Sequence
             * @description Explicit startup steps (legacy / escape hatch)
             */
            startup_sequence?: components["schemas"]["CommandStep"][];
        };
        /**
         * ScenarioResponse
         * @description Base response model for scenario operations.
         */
        ScenarioResponse: {
            /**
             * Manual Steps
             * @default []
             */
            manual_steps: {
                [key: string]: unknown;
            }[];
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
        /**
         * ScenarioState
         * @description Runtime state of a scenario.
         */
        ScenarioState: {
            /**
             * Devices
             * @description Current state of all devices in the scenario
             */
            devices?: {
                [key: string]: components["schemas"]["DeviceState"];
            };
            /**
             * Scenario Id
             * @description ID of the active scenario
             */
            scenario_id: string;
        };
        /**
         * ScenarioWBConfig
         * @description Virtual WB configuration generated from scenario definition.
         *
         *     This model creates a virtual BaseDeviceConfig-compatible configuration
         *     from scenario definitions without modifying scenario config files.
         *     Uses scenario_id as device_id and name as device_name for virtual abstraction.
         */
        ScenarioWBConfig: {
            /**
             * Commands
             * @description Virtual commands generated from scenario structure
             */
            commands?: {
                [key: string]: components["schemas"]["StandardCommandConfig"];
            };
            /**
             * Config Class
             * @description Config type identifier
             * @default ScenarioWBConfig
             */
            config_class: string;
            /**
             * Device Class
             * @description Virtual device class
             * @default Scenario
             */
            device_class: string;
            /**
             * Device Id
             * @description Maps to scenario_id
             */
            device_id: string;
            /**
             * Device Name
             * @description Maps to scenario.name
             */
            device_name: string;
            /**
             * Enable Wb Emulation
             * @description Enable WB virtual device
             * @default true
             */
            enable_wb_emulation: boolean;
            /**
             * Wb Controls
             * @description Custom WB control overrides
             * @default null
             */
            wb_controls: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /**
             * Wb State Mappings
             * @description State synchronization mappings
             * @default null
             */
            wb_state_mappings: {
                [key: string]: string | string[];
            } | null;
        };
        /**
         * ServiceInfo
         * @description Schema for service information.
         */
        ServiceInfo: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ShutdownScenarioRequest
         * @description Request model for shutting down a scenario.
         */
        ShutdownScenarioRequest: {
            /**
             * Graceful
             * @default true
             */
            graceful: boolean;
            /** Id */
            id: string;
        };
        /**
         * StandardCommandConfig
         * @description Standard command configuration with no additional fields.
         */
        StandardCommandConfig: {
            /**
             * Action
             * @description Action identifier for this command
             */
            action?: string | null;
            /**
             * Description
             * @description Human-readable description of the command
             */
            description?: string | null;
            /**
             * Group
             * @description Functional group this command belongs to
             */
            group?: string | null;
            /**
             * Params
             * @description Parameter definitions for this command
             */
            params?: components["schemas"]["CommandParameterDefinition"][] | null;
        };
        /**
         * StartScenarioRequest
         * @description Request model for starting a scenario.
         */
        StartScenarioRequest: {
            /** Id */
            id: string;
        };
        /**
         * SwitchScenarioRequest
         * @description Request model for switching scenarios.
         */
        SwitchScenarioRequest: {
            /**
             * Graceful
             * @default true
             */
            graceful: boolean;
            /** Id */
            id: string;
        };
        /**
         * SystemConfig
         * @description Schema for system configuration.
         */
        SystemConfig: {
            /**
             * Device Directory
             * @description Directory containing device configuration files
             * @default devices
             */
            device_directory: string;
            /** Devices */
            devices?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** Groups */
            groups?: {
                [key: string]: string;
            };
            /** Log File */
            log_file: string;
            /** Log Level */
            log_level: string;
            /** Loggers */
            loggers?: {
                [key: string]: string;
            } | null;
            /** @description Maintenance configuration settings */
            maintenance?: components["schemas"]["MaintenanceConfig"] | null;
            mqtt_broker: components["schemas"]["MQTTBrokerConfig"];
            persistence?: components["schemas"]["PersistenceConfig"];
            /**
             * Service Name
             * @description Name of the service
             * @default MQTT Web Service
             */
            service_name: string;
            /** Web Service */
            web_service: {
                [key: string]: unknown;
            };
        };
        /**
         * SystemInfo
         * @description Schema for system information.
         */
        SystemInfo: {
            /**
             * Devices
             * @description List of available devices
             */
            devices?: string[];
            /** Mqtt Broker */
            mqtt_broker: {
                [key: string]: unknown;
            };
            /**
             * Rooms
             * @description List of available rooms
             */
            rooms?: string[];
            /**
             * Scenarios
             * @description List of available scenarios
             */
            scenarios?: string[];
            /**
             * Version
             * @default 0.5.0
             */
            version: string;
        };
        /**
         * TestEventData
         * @description Test event data model for broadcasting
         */
        TestEventData: {
            /**
             * Data
             * @description Optional additional data
             * @example {
             *       "key": "value",
             *       "number": 42
             *     }
             */
            data: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description Test message content
             * @example This is a test event
             */
            message: string;
            /**
             * Timestamp
             * @description Optional timestamp for the event
             * @example 2024-01-01T12:00:00Z
             */
            timestamp: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WirenboardIRState
         * @description Schema for Wirenboard IR device state.
         */
        WirenboardIRState: {
            /** Alias */
            alias: string;
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Input
             * @default null
             */
            input: string | null;
            /** @default null */
            last_command: components["schemas"]["LastCommand"] | null;
            /**
             * Power
             * @default off
             */
            power: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    get_device_config_config_device__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseDeviceConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_device_configs_config_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["BaseDeviceConfig"];
                    };
                };
            };
        };
    };
    get_system_config_config_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfig"];
                };
            };
        };
    };
    get_all_persisted_states_devices_persisted_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedStatesResponse"];
                };
            };
        };
    };
    execute_device_action_devices__device_id__action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_actions_by_groups_devices__device_id__groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupedActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_actions_by_group_devices__device_id__groups__group_id__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_persisted_state_devices__device_id__persisted_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_state_devices__device_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devices_stream_events_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable - SSE service not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "SSE service not initialized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    scenarios_stream_events_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable - SSE service not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "SSE service not initialized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_sse_stats_events_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection statistics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "active_connections": {
                     *         "devices": 3,
                     *         "scenarios": 1,
                     *         "system": 2
                     *       },
                     *       "channels": [
                     *         "devices",
                     *         "scenarios",
                     *         "system"
                     *       ],
                     *       "total_connections": 6
                     *     }
                     */
                    "application/json": components["schemas"]["SSEStats"];
                };
            };
            /** @description Service Unavailable - SSE service not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "SSE service not initialized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    system_stream_events_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable - SSE service not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "SSE service not initialized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    test_broadcast_events_test__channel__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description SSE channel to broadcast to
                 * @example devices
                 */
                channel: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "data": {
                 *         "sequence": 1,
                 *         "test": true
                 *       },
                 *       "message": "This is a test event",
                 *       "timestamp": "2024-01-01T12:00:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["TestEventData"];
            };
        };
        responses: {
            /** @description Test event broadcasted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "active_connections": 3,
                     *       "message": "Test event broadcasted to devices channel",
                     *       "status": "success"
                     *     }
                     */
                    "application/json": components["schemas"]["BroadcastResponse"];
                };
            };
            /** @description Invalid channel name provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "Invalid channel: invalid_channel"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable - SSE service not initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "SSE service not initialized"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    get_groups_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    publish_message_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MQTTMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MQTTPublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service not fully initialized */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reload_system_reload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadResponse"];
                };
            };
        };
    };
    list_rooms_room_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDefinitionResponse"][];
                };
            };
        };
    };
    get_room_room__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenarios_for_room_scenario_definition_get: {
        parameters: {
            query?: {
                /** @description Filter scenarios by room ID */
                room?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDefinition"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_definition_scenario_definition__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_role_action_scenario_role_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_scenario_scenario_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShutdownScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scenario_scenario_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_state_scenario_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
        };
    };
    switch_scenario_scenario_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_virtual_config_scenario_virtual_config__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioWBConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_scenario_virtual_configs_scenario_virtual_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ScenarioWBConfig"];
                    };
                };
            };
        };
    };
    get_specific_scenario_state_scenario__scenario_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_info_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
}
