name: Build ARM Docker Image

on:
  push:
    branches: [ main, code_structure ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout frontend repo
      uses: actions/checkout@v4

    - name: Checkout config repo (public)
      uses: actions/checkout@v4
      with:
        repository: droman42/wb-mqtt-bridge
        path: wb-mqtt-bridge
        ref: main

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('wb-mqtt-bridge/pyproject.toml', 'wb-mqtt-bridge/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install and test wb-mqtt-bridge package
      shell: bash
      run: |
        set -e  # Exit on any error
        
        # Create virtual environment
        python3 -m venv /tmp/wb-mqtt-env
        
        # Use explicit paths to virtual environment executables
        VENV_PYTHON="/tmp/wb-mqtt-env/bin/python3"
        VENV_PIP="/tmp/wb-mqtt-env/bin/pip"
        
        echo "Created virtual environment with Python: $VENV_PYTHON"
        
        # Upgrade essential tools using explicit paths
        $VENV_PIP install --upgrade pip setuptools wheel
        
        # Install wb-mqtt-bridge package in editable mode
        cd wb-mqtt-bridge
        $VENV_PIP install -e .
        cd ..
        
        # Verify package installation
        echo "Verifying package installation..."
        $VENV_PIP show wb-mqtt-bridge
        
        # Test imports using explicit Python path
        echo "Testing package imports..."
        $VENV_PYTHON -c "import wb_mqtt_bridge; print('✅ Package imported:', wb_mqtt_bridge.__file__)"
        $VENV_PYTHON -c "from wb_mqtt_bridge.domain.devices.models import WirenboardIRState; print('✅ Device models imported')"
        
        # Export the Python executable path for subsequent steps
        echo "VENV_PYTHON=$VENV_PYTHON" >> $GITHUB_ENV

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Generate types and validate
      shell: bash
      run: |
        set -e  # Exit on any error
        
        # Verify virtual environment Python is available
        echo "Using virtual environment Python: $VENV_PYTHON"
        
        # Final verification of package imports using explicit path
        echo "Final package verification:"
        $VENV_PYTHON -c "import wb_mqtt_bridge; print('✅ Package location:', wb_mqtt_bridge.__file__)"
        $VENV_PYTHON -c "from wb_mqtt_bridge.domain.devices.models import WirenboardIRState; print('✅ Device models ready')"
        
        # Set environment for npm scripts to use virtual environment Python
        export PYTHON_EXECUTABLE="$VENV_PYTHON"
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        
        echo "Using Python executable: $PYTHON_EXECUTABLE"
        
        # Run type generation (package mode only - CI must use package-based imports)
        echo "Running package-based type generation..."
        npm run gen:device-pages -- --batch --mode=package --mapping-file=config/device-state-mapping.json --generate-router

    - name: Run TypeScript validation
      run: |
        npm run typecheck:all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build ARM Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm/v7
        tags: wb-mqtt-ui:latest
        outputs: type=docker,dest=/tmp/wb-mqtt-ui.tar
        build-args: |
          BUILDKIT_INLINE_CACHE=1

    - name: Compress Docker image
      run: |
        gzip /tmp/wb-mqtt-ui.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: wb-mqtt-ui-image
        path: /tmp/wb-mqtt-ui.tar.gz
        retention-days: 30

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          npm-debug.log*
          yarn-error.log*
        retention-days: 7 